# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ARZhihuDaily' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ARZhihuDaily
  pod 'ReactiveCocoa', '~>2.1.8'
  pod 'AFNetworking', '~> 2.5.4'
  pod 'SDWebImage', '~> 4.0'
  pod 'MJExtension'
end
